// src/main/java/bdo/Faith/src/main/Faith/assets/js/plugins/Spread.Sheets.v14.0.1.Designer/samples/vue/src/App.vue
<template>
  <div id="app">
    <gc-spread-sheets-designer :styleInfo='styleInfo' :config='config' @designerInitialized='designerInitialized'>
    </gc-spread-sheets-designer>
  </div>
</template>

<script>

  import '@grapecity/spread-sheets/styles/gc.spread.sheets.excel2013white.css'
  import '@grapecity/spread-sheets-designer/styles/gc.spread.sheets.designer.min.css'
  import '@grapecity/spread-sheets-designer-resources-cn';
  import GC from '@grapecity/spread-sheets';
  GC.Spread.Common.CultureManager.culture("zh-cn");
  import '@grapecity/spread-sheets-resources-zh';
 
  import { Designer } from '@grapecity/spread-sheets-designer-vue'

  export default {
    name: 'App',
    data: function () {
      return {
        styleInfo: { height: "98vh", width: '100%' },
        config: null,
        designer: null
      };
    },
    methods: {
      designerInitialized(value) {
        this.designer = value;

      }
    }
  }
</script>
<style>
</style>

// src/main/java/bdo/Faith/src/main/Faith/assets/js/plugins/Spread.Sheets.v14.0.1.Designer/samples/react/src/App.js
import React from 'react';
import '@grapecity/spread-sheets-resources-zh';
import '@grapecity/spread-sheets-designer-resources-cn';
import * as GC from '@grapecity/spread-sheets';
import {Designer} from '@grapecity/spread-sheets-designer-react';
import "@grapecity/spread-sheets-designer/styles/gc.spread.sheets.designer.min.css"
import "@grapecity/spread-sheets/styles/gc.spread.sheets.excel2013white.css"

GC.Spread.Common.CultureManager.culture('zh-cn');

function App() {
  return (
    <Designer styleInfo = {{"100%", height: '98vh'}}></Designer>
  )
}

export default App;
